### ISSUE TITLE
No such file or directory: 'weights/transformerocr.pth'

### ISSUE THREAD

**Issue by vinhprs** [tuanio/test-vietocr#1]
![image](https://user-images.githubusercontent.com/77932499/195283957-b44f4002-493a-4023-a0b7-91fc34ca944f.png)

Nó bị lỗi như này anh ạ

**Comment by tuanio** [comment]
Em tải ở đây nha https://github.com/pbcquoc/vietocr

**Comment by vinhprs** [comment]
Anh ơi em clone về máy windows chạy ok nhưng deploy heroku bị lỗi ạ. Anh có deploy được không anh?

**Comment by tuanio** [comment]
> Anh ơi em clone về máy windows chạy ok nhưng deploy heroku bị lỗi ạ. Anh có deploy được không anh?

hiện tại heroku đang tính phí rồi ấy. Em có thể thử deploy ở railway, cũng PaaS, nhưng free
